### ISSUE TITLE
FATAL EXCEPTION in production app

### ISSUE THREAD

**Issue by marcolino** [zsajjad/react-facebook-pixel#18]
I did use react-facebook-pixel to log my react-native app purchase events to Facebook Pixel.
Building in development mode it seems working flawlessy (even if I cannot see events in FB pixel console... :-().
When building in production mode (`__DEV__ === false`) the app crashes after the ReactPixel.init() function is run.
This is the relevant code in App.js:

    ...
    import ReactPixel from 'react-facebook-pixel';
    ...
    ReactPixel.init(''20297591729****', {}, { autoConfig: false, debug: true }); // => crash in PRODUCTION

The relevant error seems to be: **`Can't find variable: Alert`**

Logcat:
```
2019-02-11 17:58:10.114 14385-14449/? I/ReactNativeJS: Running application "Myapp" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
2019-02-11 17:58:10.162 14385-14449/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.myapp, PID: 14385
    java.lang.RuntimeException: Error calling AppRegistry.runApplication
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:166)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: com.facebook.jni.CppException: Exception calling object as function: Can't find variable: Alert (<unknown file>:307)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:166) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:784) 
2019-02-11 17:58:10.173 854-3792/? W/ActivityManager:   Force finishing activity com.myapp/.MainActivity
```

Did you ever experience any error of this kind?

**UPDATE**
Debugging the issue, I think the problem is related to the fact that we have no '`document`' in react-native...

**Comment by zsajjad** [comment]
Same as #16
